# Generated by Django 2.2.2 on 2019-10-17 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemEmpresa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rutempresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('razonsocialempresa', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mem_empresa2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemAno',
            fields=[
                ('codigoano', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'mem_ano',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemDesextremosclimaticos',
            fields=[
                ('codigoindicador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreindicador', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionindicador', models.CharField(blank=True, max_length=20, null=True)),
                ('medidaindicador', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_desextremosclimaticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemDia',
            fields=[
                ('codigodia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'mem_dia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemEstacionmeteorologica',
            fields=[
                ('codigoestacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('longitudestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('latitudestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('alturaestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('medicionestacion', models.CharField(max_length=20)),
                ('estadoestacion', models.BooleanField(default=True, verbose_name='EstadoEstacion')),
            ],
            options={
                'db_table': 'mem_estacionmeteorologica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemUbicacion',
            fields=[
                ('codigoubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreubicacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_ubicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemUsuario',
            fields=[
                ('rutusuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(blank=True, max_length=20, null=True)),
                ('cargousuario', models.BooleanField(default=True, verbose_name='CargoUsuario')),
                ('contrasenausuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estadousuario', models.BooleanField(default=True, verbose_name='EstadoUsuario')),
                ('rutempresa', models.ForeignKey(db_column='rutempresa', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mem_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemSeriedetiempo',
            fields=[
                ('codigoserie', models.AutoField(primary_key=True, serialize=False)),
                ('fechaserie', models.DateField(blank=True, null=True)),
                ('temperaturamaxserie', models.CharField(blank=True, max_length=20, null=True)),
                ('temperaturaminserie', models.CharField(blank=True, max_length=20, null=True)),
                ('temperaturamediaserie', models.CharField(blank=True, max_length=20, null=True)),
                ('precipitacionserie', models.CharField(blank=True, max_length=20, null=True)),
                ('codigoestacion', models.ForeignKey(blank=True, db_column='codigoestacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica')),
            ],
            options={
                'db_table': 'mem_seriedetiempo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemMes',
            fields=[
                ('codigomes', models.AutoField(primary_key=True, serialize=False)),
                ('nombremes', models.CharField(blank=True, max_length=20, null=True)),
                ('codigoano', models.ForeignKey(db_column='codigoano', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemAno')),
            ],
            options={
                'db_table': 'mem_mes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemIndicesextremosclimaticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('csdi', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cwd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dtr', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fd0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('gsl', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('id0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('prcptot', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r10mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r20mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r95p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r99p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r50mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rx1day', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rx5day', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sdii', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('su25', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tn10p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tn90p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tnn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('txn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tr20', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tx10p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tx90p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tnx', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('txx', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wsdi', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('codigoano', models.ForeignKey(blank=True, db_column='codigoano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemAno')),
                ('codigoestacion', models.ForeignKey(blank=True, db_column='codigoestacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica')),
                ('codigoindicador', models.ForeignKey(blank=True, db_column='codigoindicador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemDesextremosclimaticos')),
            ],
            options={
                'db_table': 'mem_indicesextremosclimaticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemHora',
            fields=[
                ('codigohora', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('codigodia', models.ForeignKey(db_column='codigodia', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemDia')),
            ],
            options={
                'db_table': 'mem_hora',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='codigoubicacion',
            field=models.ForeignKey(blank=True, db_column='codigoubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemUbicacion'),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='rutusuario',
            field=models.ForeignKey(db_column='rutusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemUsuario'),
        ),
        migrations.AddField(
            model_name='memdia',
            name='codigomes',
            field=models.ForeignKey(db_column='codigomes', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemMes'),
        ),
        migrations.CreateModel(
            name='MemBitacora',
            fields=[
                ('codigobitacora', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionbitacora', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechainiciobitacora', models.DateField(blank=True, null=True)),
                ('fechafinbitacora', models.DateField(blank=True, null=True)),
                ('codigoestacion', models.ForeignKey(db_column='codigoestacion', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica')),
            ],
            options={
                'db_table': 'mem_bitacora',
                'managed': True,
            },
        ),
    ]
