# Generated by Django 2.2.2 on 2019-06-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemAno',
            fields=[
                ('codigoano', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ano', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'mem_ano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemBitacora',
            fields=[
                ('codigobitacora', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcionbitacora', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechainiciobitacora', models.DateField(blank=True, null=True)),
                ('fechafinbitacora', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mem_bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemDesextremosclimaticos',
            fields=[
                ('codigoindicador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreindicador', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionindicador', models.CharField(blank=True, max_length=20, null=True)),
                ('medidaindicador', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_desextremosclimaticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemDia',
            fields=[
                ('codigodia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dia', models.DateField()),
            ],
            options={
                'db_table': 'mem_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemEmpresa',
            fields=[
                ('rutempresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('razonsocialempresa', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasenaempresa', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemEstacionmeteorologica',
            fields=[
                ('codigoestacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('longitudestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('latitudestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('alturaestacion', models.CharField(blank=True, max_length=20, null=True)),
                ('medicionestacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mem_estacionmeteorologica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemHora',
            fields=[
                ('codigohora', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'mem_hora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemIndicesextremosclimaticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('csdi', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cwd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('dtr', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fd0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('gsl', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('id0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('prcptot', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r10mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r20mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r95p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r99p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('r50mm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rx1day', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rx5day', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sdii', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('su25', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tn10p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tn90p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tnn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('txn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tr20', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tx10p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tx90p', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tnx', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('txx', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wsdi', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'mem_indicesextremosclimaticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemMes',
            fields=[
                ('codigomes', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombremes', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_mes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemSeriedetiempo',
            fields=[
                ('codigoserie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechaserie', models.DateField(blank=True, null=True)),
                ('temperaturamaxserie', models.CharField(blank=True, max_length=20, null=True)),
                ('temperaturaminserie', models.CharField(blank=True, max_length=20, null=True)),
                ('temperaturamediaserie', models.CharField(blank=True, max_length=20, null=True)),
                ('precipitacionserie', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_seriedetiempo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemUbicacion',
            fields=[
                ('codigoubicacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreubicacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemUsuario',
            fields=[
                ('rutusuario', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(blank=True, max_length=20, null=True)),
                ('cargousuario', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasenausuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_usuario',
                'managed': False,
            },
        ),
    ]
