# Generated by Django 2.2.2 on 2020-03-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memempresa',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
