# Generated by Django 2.2.2 on 2020-04-04 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='comentario',
            field=models.CharField(default=datetime.date.today, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='cuenca',
            field=models.CharField(default=datetime.date.today, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='fechainstalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='fechatermino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='rio',
            field=models.CharField(default=datetime.date.today, max_length=20),
            preserve_default=False,
        ),
    ]
