# Generated by Django 2.1 on 2020-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestadisticas',
            name='intecuartilmax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='intecuartilmin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='intecuartilpre',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
    ]
