# Generated by Django 2.2.2 on 2019-10-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memempresa',
            table='mem_empresa',
        ),
    ]
