# Generated by Django 2.2.2 on 2021-07-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemDesextremosclimaticos',
        ),
    ]
