# Generated by Django 2.2.2 on 2019-07-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memempresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memestacionmeteorologica',
            options={},
        ),
    ]
