# Generated by Django 2.2.2 on 2021-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memseriedetiempo',
            name='temperaturamedserie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
