# Generated by Django 2.1 on 2020-11-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_auto_20201111_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestadisticas',
            name='atipicoinfmax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='atipicoinfmin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='atipicoinfpre',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
    ]
