# Generated by Django 2.2.2 on 2021-07-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_delete_memdesextremosclimaticos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemPaisUbicacion',
            fields=[
                ('codigopais', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepais', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mem_pais_ubicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemRegionUbicacion',
            fields=[
                ('codigoregion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregion', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.ForeignKey(blank=True, db_column='pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemPaisUbicacion')),
            ],
            options={
                'db_table': 'mem_region_ubicacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='memubicacion',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemRegionUbicacion'),
        ),
    ]
