# Generated by Django 2.2.2 on 2020-04-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_auto_20200404_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memhora',
            name='codigodia',
        ),
        migrations.RemoveField(
            model_name='memindicesextremosclimaticos',
            name='codigoano',
        ),
        migrations.RemoveField(
            model_name='memindicesextremosclimaticos',
            name='codigoindicador',
        ),
        migrations.AddField(
            model_name='memindicesextremosclimaticos',
            name='codigomes',
            field=models.ForeignKey(blank=True, db_column='codigomes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemMes'),
        ),
        migrations.DeleteModel(
            name='MemDia',
        ),
        migrations.DeleteModel(
            name='MemHora',
        ),
    ]
