# Generated by Django 2.2.2 on 2021-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_memseriedetiempo_temperaturamedserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='cdd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='csdi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='cwd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='dtr',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='fd0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='gsl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='gsl2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='id0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='prcptot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='premax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='r10mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='r20mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='r50mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='r95p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='r99p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='rx1day',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='rx5day',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='sdii',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='su25',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='temmax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='temmin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tn10p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tn90p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tnn',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tnx',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tr20',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tx10p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='tx90p',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='txn',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='txx',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='memindicesextremosclimaticos',
            name='wsdi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
    ]
