# Generated by Django 2.2.2 on 2020-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_auto_20200322_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='memano',
            name='nombre',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memempresa',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
