# Generated by Django 2.2.2 on 2019-07-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_auto_20190719_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='memempresa',
            name='estadoempresa',
            field=models.BooleanField(default=True, verbose_name='estadoempresa'),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='codigoserie',
            field=models.ForeignKey(blank=True, db_column='codigoserie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemSeriedetiempo'),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='codigoubicacion',
            field=models.ForeignKey(blank=True, db_column='codigoubicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemUbicacion'),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='estadoestacion',
            field=models.BooleanField(default=True, verbose_name='EstadoEstacion'),
        ),
        migrations.AddField(
            model_name='memestacionmeteorologica',
            name='rutusuario',
            field=models.ForeignKey(db_column='rutusuario', default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemUsuario'),
            preserve_default=False,
        ),
    ]
