# Generated by Django 2.2.2 on 2021-10-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_auto_20211019_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='memindicesextremosclimaticos',
            name='periodoFin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memindicesextremosclimaticos',
            name='periodoInicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
