# Generated by Django 2.2.2 on 2021-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_auto_20210703_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mempaisubicacion',
            name='nombrepais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memregionubicacion',
            name='nombreregion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memubicacion',
            name='nombreubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
