# Generated by Django 2.2.2 on 2019-07-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_auto_20190719_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memusuario',
            options={'managed': True},
        ),
    ]
