# Generated by Django 2.2.2 on 2020-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_auto_20200404_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memano',
            name='ano',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
    ]
