# Generated by Django 2.2.2 on 2020-03-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_remove_memano_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memano',
            name='ano',
            field=models.CharField(default=113, max_length=30),
            preserve_default=False,
        ),
    ]
