# Generated by Django 2.2.2 on 2020-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_auto_20200405_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memmes',
            name='nombremes',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
    ]
