# Generated by Django 2.2.2 on 2021-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_auto_20210202_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestadisticas',
            name='extremoinfmax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='extremoinfmin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='extremoinfpre',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='extremosupmax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='extremosupmin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='extremosuppre',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
    ]
