# Generated by Django 2.2.2 on 2021-07-04 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_auto_20210703_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membitacora',
            name='rutusuario',
            field=models.ForeignKey(db_column='rutusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memestacionmeteorologica',
            name='rutusuario',
            field=models.ForeignKey(db_column='rutusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
