# Generated by Django 2.2.2 on 2021-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20210202_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestmax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestmin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestpmax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestpmin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestppre',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kstestpre',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True),
        ),
    ]
