# Generated by Django 2.2.2 on 2021-07-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20210703_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memestacionmeteorologica',
            name='rutusuario',
            field=models.ForeignKey(blank=True, db_column='rutusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
