# Generated by Django 2.0.6 on 2020-06-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20200405_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemDia',
            fields=[
                ('codigodia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True)),
                ('codigomes', models.ForeignKey(db_column='codigomes', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemMes')),
            ],
            options={
                'db_table': 'mem_dia',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='memindicesextremosclimaticos',
            name='codigomes',
        ),
        migrations.AddField(
            model_name='membitacora',
            name='rutusuario',
            field=models.ForeignKey(db_column='rutusuario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemUsuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memindicesextremosclimaticos',
            name='codigoano',
            field=models.ForeignKey(blank=True, db_column='codigoano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemAno'),
        ),
    ]
