# Generated by Django 2.2.2 on 2020-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20200322_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memano',
            name='codigoano',
        ),
        migrations.AddField(
            model_name='memano',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
