# Generated by Django 2.2.2 on 2019-08-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20190818_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memempresa',
            old_name='nombreempresa',
            new_name='nombreempresa1',
        ),
    ]
