# Generated by Django 2.2.2 on 2019-08-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0006_auto_20190818_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memempresa',
            old_name='nombreempresa1',
            new_name='nombreempresa',
        ),
    ]
