# Generated by Django 2.2.2 on 2021-07-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0006_auto_20210703_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemUsuario',
        ),
    ]
