# Generated by Django 2.0.6 on 2020-06-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0006_auto_20200609_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membitacora',
            name='fechainiciobitacora',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
