# Generated by Django 2.0.6 on 2020-06-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0007_auto_20200611_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='memindicesextremosclimaticos',
            name='gsl2',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
    ]
