# Generated by Django 2.2.2 on 2021-07-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0007_delete_memusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='memempresa',
            name='empresa_padre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memEmpresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
