# Generated by Django 2.2.2 on 2019-08-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0007_auto_20190818_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memempresa',
            name='estadoempresa',
        ),
    ]
