# Generated by Django 2.2.2 on 2021-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0008_memempresa_empresa_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='memempresa',
            name='is_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
