# Generated by Django 2.2.2 on 2019-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0008_remove_memempresa_estadoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membitacora',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memdia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memhora',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memmes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memseriedetiempo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memubicacion',
            options={},
        ),
        migrations.AlterField(
            model_name='memempresa',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memestacionmeteorologica',
            name='codigoestacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
