# Generated by Django 2.2.2 on 2021-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0008_auto_20210301_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='memestadisticas',
            name='kurtosismax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kurtosismin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='memestadisticas',
            name='kurtosispre',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True),
        ),
    ]
