# Generated by Django 2.0.6 on 2020-07-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0009_auto_20200630_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memseriedetiempo',
            name='temperaturamediaserie',
        ),
    ]
