# Generated by Django 2.2.2 on 2021-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0009_memempresa_is_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='memregionubicacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memregionubicacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
