# Generated by Django 2.2.2 on 2019-09-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0009_auto_20190828_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membitacora',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memdesextremosclimaticos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memdia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memempresa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memestacionmeteorologica',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memhora',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memindicesextremosclimaticos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memmes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memseriedetiempo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memubicacion',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='memestacionmeteorologica',
            name='codigoserie',
        ),
        migrations.AddField(
            model_name='membitacora',
            name='codigoestacion',
            field=models.ForeignKey(db_column='codigoestacion', default='%2019-%01-%01 %00:%00:%00', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memdia',
            name='codigomes',
            field=models.ForeignKey(db_column='codigomes', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemMes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memhora',
            name='codigodia',
            field=models.ForeignKey(db_column='codigodia', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemDia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memmes',
            name='codigoano',
            field=models.ForeignKey(db_column='codigoano', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemAno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memseriedetiempo',
            name='codigoestacion',
            field=models.ForeignKey(blank=True, db_column='codigoestacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica'),
        ),
        migrations.AlterField(
            model_name='membitacora',
            name='codigobitacora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memdia',
            name='codigodia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memdia',
            name='dia',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AlterField(
            model_name='memhora',
            name='codigohora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memhora',
            name='hora',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='memmes',
            name='codigomes',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memseriedetiempo',
            name='codigoserie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memubicacion',
            name='codigoubicacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
