# Generated by Django 2.2.2 on 2021-07-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0010_auto_20210726_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memseriedetiempo',
            name='precipitacionserie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memseriedetiempo',
            name='temperaturamaxserie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memseriedetiempo',
            name='temperaturaminserie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
