# Generated by Django 2.0.6 on 2020-07-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0010_remove_memseriedetiempo_temperaturamediaserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemEstadisticas',
            fields=[
                ('codigoestadisticas', models.AutoField(primary_key=True, serialize=False)),
                ('mediamax', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('mediamin', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('mediapre', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('medianamax', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('medianamin', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('medianapre', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('modamax', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('modamin', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('modapre', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('desviacionesmax', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('desviacionesmin', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('desviacionespre', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('varianzamax', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('varianzamin', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('varianzapre', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('codigoano', models.ForeignKey(db_column='codigoano', on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemAno')),
                ('codigoestacion', models.ForeignKey(blank=True, db_column='codigoestacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memoria.MemEstacionmeteorologica')),
            ],
            options={
                'db_table': 'mem_estadisticas',
                'managed': True,
            },
        ),
    ]
